package student.onlineretailer.repo

import student.onlineretailer.data.ProductSuggestion
import javax.transaction.Transactional


interface ProductSuggestionRepository {
    // Get all product suggestions from the database.
    fun getProductSuggestions(): Collection<ProductSuggestion>

    // Get the product suggestion with the specified ID.
    // Return null if there is no product with the specified ID.
    fun getProductSuggestions(id: Long): ProductSuggestion?

    // Insert a new product suggestion into the database.
    // Return the ID generated by the database upon insertion.
    @Transactional
    fun insertProductSuggestion(ps: ProductSuggestion): Long

    // Modify the price of the specified product suggestion in the database.
    // Return true if successful, or false if there is no product with the specified ID.
    @Transactional
    fun modifyPrice(id: Long, newPrice: Double): Boolean

    // Modify the expected sales of the specified product suggestion in the database.
    // Return true if successful, or false if there is no product with the specified ID.
    @Transactional
    fun modifySales(id: Long, newSales: Long): Boolean

    // Delete all product suggestions from the database.
    @Transactional
    fun deleteProductSuggestions()
}