#management:
#  endpoints:
#    web:
#      exposure:
#        include: \*

onlineRetailer:
  salesTaxRate: 0.20
  deliveryCharge:
    normal: 2.50
    threshold: 3000

spring:
  cache:
    type: redis
  rabbitmq: # https://spring.io/guides/gs/messaging-rabbitmq/
    host: localhost
    port: 5672
    username: user
  kafka:
    listener:
      missing-topics-fatal: false
---
resources:
  db: H2
  logs: C:\temp\logs\
  secure: false
spring:
  config:
    activate:
      on-profile: development
---
resources:
  db: Oracle
  logs: //PROD_SERVER/logs/
  secure: true
spring:
  config:
    activate:
      on-profile: production
---
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springbootdb
    username: root
    password: TODO_GET_THIS_SECURELY
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  config:
    activate:
      on-profile: mariadb
